import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache Google Fonts (same as before)
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 })],
  })
);
registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'gstatic-fonts-cache',
    plugins: [new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 })],
  })
);

// ── Air-Gapped Kill Switch ───────────────────────────────────────
let isStrictPrivateMode = false;

// Listen for messages from the main app
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SET_PRIVATE_MODE') {
    isStrictPrivateMode = event.data.enabled;
    console.log(`[SW] Strict Private Mode is now ${isStrictPrivateMode ? 'ENABLED' : 'DISABLED'}`);
  }
});

// Intercept all outgoing requests
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // If Air-Gapped Mode is ON, block requests that leave the local origin
  if (isStrictPrivateMode) {
    const isLocal = url.hostname === 'localhost' || url.hostname === '127.0.0.1' || url.origin === self.location.origin;
    
    if (!isLocal) {
      console.warn(`[SW] Blocked outgoing request to ${url.href} due to Air-Gapped Mode.`);
      event.respondWith(
        new Response('Blocked by Air-Gapped Kill-Switch', {
          status: 403,
          statusText: 'Forbidden: App is in Strict Private Mode',
          headers: { 'Content-Type': 'text/plain' }
        })
      );
      return;
    }
  }

  // Continue normally if not blocked
});
